# name of workflow
name: first workflow 

# define when workflow works
on: 
	# allows you to run this workflow manually from the Actions tab
	workflow_dispatch

jobs:
  first-job:
    # define where runner works
    runs-on:
      ubuntu-latest
    steps:
      # define name of step
      - name: 
        print hello

        # execute shell script or an action
        run:
          echo "hello world!"
      - name:
        print goodbye
        run:
          echo "done - goodbye"
